version: '3'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - '2181:2181'

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - '9092:9092'
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      mongo:
      image: mongo
      container_name: mongo
      ports:
      - '27017:27017'
  employee-service:
     container_name: employee-service
     build: ./employee
     ports:
       - 8081:8081
     environment:
       - PORT: 8081
       - MONGO_URL=mongodb://mongo:27017/employee
       - KAFKA_BOOTSRAP_SERVERS=kafka:9092
       - KAFKA_TOPIC=employee-topic
     depends_on:
       - kafka
       - mongo


